[display]
viewport=1280x720
fullscreen=false

[gource]
title=Option Sentinel
seconds-per-day=2
auto-skip-seconds=1
elasticity=0.3
font-size=18
hide=mouse
date-format=%Y-%m-%d
highlight-users=true
multi-sampling=true
stop-at-end=true
