"""initial schema

Revision ID: 5f53c99463d7
Revises: 
Create Date: 2026-04-29 22:17:24.370089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f53c99463d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('access_expiry', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('refresh_expiry', sa.DateTime(), nullable=False),
    sa.Column('re_auth_required', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binary_event_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spread',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.Enum('put_credit_spread', 'call_credit_spread', 'iron_condor', 'vertical', 'custom', name='spreadstrategytype'), nullable=False),
    sa.Column('net_credit_received', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('maximum_profit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('maximum_loss', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_type', sa.Enum('iv_crush', 'earnings_fade', 'directional_momentum', 'mean_reversion', 'custom', name='thesistemplatetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alignment_rating', sa.Enum('aligned', 'partially_aligned', 'misaligned', 'unrated', name='alignmentrating'), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='thesisstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schwab_account_id', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=21), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=False),
    sa.Column('option_type', sa.Enum('call', 'put', name='optiontype'), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('opening_credit_debit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_mark', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unrealised_pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('days_to_expiry', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='positionstatus'), nullable=False),
    sa.Column('thesis_id', sa.String(length=36), nullable=True),
    sa.Column('spread_id', sa.String(length=36), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spread_id'], ['spread.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_position_open_symbol_account', 'position', ['symbol', 'schwab_account_id'], unique=True, sqlite_where=sa.text("status = 'open'"))
    op.create_table('alert',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('profit_target', 'expiry_14d', 'expiry_7d', 'expiry_3d', 'binary_event_exit', name='alerttype'), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('spread_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alertseverity'), nullable=False),
    sa.Column('trigger_timestamp', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.Enum('pending', 'delivered', 'failed', 'max_retries', name='deliverystatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['spread_id'], ['spread.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_type', 'position_id', name='uq_alert_daily_position')
    )
    op.create_table('exit_goal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('profit_target_pct', sa.Float(), nullable=True),
    sa.Column('dte_threshold', sa.Integer(), nullable=True),
    sa.Column('underlying_price_target', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_target_direction', sa.Enum('above', 'below', name='pricetargetdirection'), nullable=True),
    sa.Column('exit_proximity_score', sa.Integer(), nullable=False),
    sa.Column('last_scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    op.create_table('greeks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('delta_source', sa.Enum('api', 'calculated', 'unavailable', name='sourceenum'), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('gamma_source', sa.Enum('api', 'calculated', 'unavailable', name='sourceenum'), nullable=False),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('theta_source', sa.Enum('api', 'calculated', 'unavailable', name='sourceenum'), nullable=False),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('vega_source', sa.Enum('api', 'calculated', 'unavailable', name='sourceenum'), nullable=False),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('iv_source', sa.Enum('api', 'calculated', 'unavailable', name='sourceenum'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeks')
    op.drop_table('exit_goal')
    op.drop_table('alert')
    op.drop_index('uq_position_open_symbol_account', table_name='position', sqlite_where=sa.text("status = 'open'"))
    op.drop_table('position')
    op.drop_table('thesis')
    op.drop_table('spread')
    op.drop_table('binary_event_flag')
    op.drop_table('auth_token')
    # ### end Alembic commands ###
